version: 2
updates:
  - package-ecosystem: pip
    directory: /labs/shodan-excel-analytics
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directory: /labs/classificador-urls-maliciosas
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
